/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ph_plsqlhelper_ClsJNIMethods */

#ifndef _Included_com_pcs_plsqlcodesample_ClsJNIMethods
#define _Included_com_pcs_plsqlcodesample_ClsJNIMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ph_plsqlhelper_ClsJNIMethods
 * Method:    fnCalcAmt
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_pcs_plsqlcodesample_ClsJNIMethods_fnCalcAmt
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_ph_plsqlhelper_ClsJNIMethods
 * Method:    fnCalcWightInGrams
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_pcs_plsqlcodesample_ClsJNIMethods_fnCalcWightInGrams
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_ph_plsqlhelper_ClsJNIMethods
 * Method:    fnConvertGramstoKiloGrams
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_pcs_plsqlcodesample_ClsJNIMethods_fnConvertGramstoKiloGrams
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_ph_plsqlhelper_ClsJNIMethods
 * Method:    fnFormatValue
 * Signature: (Landroid/content/res/AssetManager;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pcs_plsqlcodesample_ClsJNIMethods_fnFormatValue
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
